packages:
  - name: Character Design
    price: 120
    items:
      - Half body character $120
      - Full body character $160

  - name: NSFW
    price: 140
    items:
      - 1 Character $140
      - 2 Characters $200
      - 3 Characters $250
      - 4+ Characters $280

  - name: Book cover addons
    price: 15
    items:
      - Paperback / Hardback cover $45
      - Typography title $15
      - 3D Mockups of book cover $15
      - Bookmark $45

other:
